config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
  
  get 'home', to: "pages#home", as: "home"
  
  get 'about_us', to: "pages#about", as: "about"

  get 'lizards/:number', to: "pages#lizards", as: "lizards"

  get 'employees', to: 'employees#index', as: "employees"

  get 'employees/:id', to: 'employees#show', as: "employee", id: /\d+/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :name, :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
        @employees = Employee.all
    end

    def show
        @employee = Employee.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home 

    end

    def about

    end

    def lizards
        @number_of_lizards = params[:number]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/common/_header.html.erb
<header>
    <nav>
        <ul class="nav_menu">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "Employees", employees_path %></li>
            <li><%= link_to "About", about_path %></li>
        </ul>
    </nav>
</header>

app/views/employees/_employee.html.erb
<div class="employee">
    <% if(display_employee_link == true) %>
        <p><b>Name:</b><%= link_to employee.name, employee_path(employee) %></p>
    <% else %>
        <p><b>Name:</b><%= employee.name %></p>    
    <% end %>
    <p><b>Phone:</b><%= employee.phone_number%></p>
</div>

app/views/employees/index.html.erb
<h2>Employees</h2>

<% @employees.each do |employee| %>
    <%= render partial: 'employee', object: employee, locals: {display_employee_link: true} %>
<% end %>>

app/views/employees/show.html.erb
<%= render partial: 'employee', object: @employee, locals: {display_employee_link: false} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KyleIsSickChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur elementum sagittis nisl. Duis nunc metus, venenatis sit amet turpis non, pellentesque consequat justo. Curabitur scelerisque, ex vel iaculis vehicula, est justo lacinia velit, sit amet pellentesque tortor massa eu nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras dui sapien, scelerisque in tellus a, condimentum fringilla lacus. Nam augue enim, lobortis ut tortor id, vehicula gravida dui. Praesent faucibus quam in mauris semper varius. Nulla malesuada sodales lectus, vitae mollis sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. </p>

app/views/pages/home.html.erb
<h2>Home</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis elit dapibus, placerat nunc in, lobortis nisi. Morbi sit amet massa ullamcorper nunc pellentesque interdum. Sed purus tortor, rhoncus nec accumsan semper, aliquet vitae nulla. Phasellus volutpat tincidunt ultrices. Nulla lorem magna, mollis ac blandit at, auctor a lorem. Nam quis eleifend nisi. Praesent efficitur lacus augue. Nullam condimentum euismod sapien, quis molestie turpis laoreet sed. Vestibulum rhoncus vulputate ante vitae varius. Etiam ullamcorper quam nec nisi efficitur, nec ultricies erat imperdiet. Pellentesque venenatis bibendum nibh, at tempor dolor rhoncus feugiat. Phasellus a sodales metus, fermentum fermentum ex. Aenean non accumsan arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur efficitur massa dui, ut viverra est hendrerit eu. Integer sed nisl et mi rutrum imperdiet. </p>
<p>Sed iaculis arcu at consectetur placerat. Suspendisse volutpat leo ex, vitae ultrices nisi facilisis eget. Curabitur eget mauris ligula. Maecenas sed elementum tortor. Fusce lorem nunc, blandit ac faucibus vitae, finibus at sapien. Sed tempus lobortis sem sit amet tristique. Praesent ac dui et magna finibus vehicula quis quis massa. Duis sagittis eu urna non fringilla. Nulla facilisi. Aliquam non risus quis eros fermentum luctus et ut elit. Curabitur feugiat eros non diam efficitur accumsan. Nullam eros enim, luctus pellentesque nulla a, efficitur convallis arcu. Nunc tincidunt, elit quis laoreet aliquam, nulla nisl congue neque, eleifend ornare orci neque rutrum ligula. Nam tellus nisi, bibendum id pharetra at, laoreet eu ex. </p>
<p>Lizards links</p>
<ul>
    <li><%= link_to "12 Lizards", lizards_path(12) %></li>
    <li><%= link_to "444 Lizards", lizards_path(444) %></li>
    <li><%= link_to "9672 Lizards", lizards_path(9672) %></li>
</ul>

app/views/pages/lizards.html.erb
<h3>Number of Lizards</h3>
<p><%= @number_of_lizards.to_s + " lizard" + if @number_of_lizards > '1' then "s" else "" end%></p>
<% @number_of_lizards.to_i.times do %>
    <%= "\u{1f40a}" %>
<% end %>